// Generated by Hive CE
// Do not modify
// Check in to version control

import 'package:hive_ce/hive_ce.dart';
import 'package:shopnest/DataModel/CategoryUiProps.dart';
import 'package:shopnest/DataModel/ItemModel.dart';

extension HiveRegistrar on HiveInterface {
  void registerAdapters() {
    registerAdapter(ItemCategoryAdapter());
    registerAdapter(ItemmodelAdapter());
  }
}

extension IsolatedHiveRegistrar on IsolatedHiveInterface {
  void registerAdapters() {
    registerAdapter(ItemCategoryAdapter());
    registerAdapter(ItemmodelAdapter());
  }
}
